spring:
  application:
    name: hello
  cloud:
    consul:
      host: 192.168.99.100
      port: 8500
      discovery:
        prefer-ip-address: true
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
